pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    options {
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    // Build stage
    stages {
        stage('init'){
            steps {
                sh """
                    cd 01-vpc
                    terraform init -reconfigure -upgrade
                """
            }
        }
        stage('plan'){
            steps {
                sh """
                    cd 01-vpc
                    terraform plan
                """
            }
        }
        stage('apply'){
            when {
                expression { 
                    params.action == 'apply'
                }
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply
                """
            }
        }
    }
    // post build
    post {
        always {
            echo "I will always run"
        }
        success {
            echo "Runs only if pipeline is succeded"
        }
        failure {
            echo "Runs only if pipeline is failed"
        }
        changed {
            echo "Runs only if there is change in state compared to previous"
        }
    }
}